# Generated by Django 5.1.6 on 2025-02-18 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0002_alter_client_company_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('UI/UX Design', 'UI/UX Design'), ('Website Design', 'Website Design'), ('Web App Development', 'Web App Development'), ('SEO', 'SEO'), ('Social Media', 'Social Media'), ('Backend Development', 'Backend Development'), ('Digital Marketing', 'Digital Marketing'), ('Other', 'Other')], max_length=255, null=True)),
                ('project_lead', models.CharField(blank=True, max_length=255, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='project_logos/')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.CharField(blank=True, choices=[('Highest', 'Highest'), ('Medium', 'Medium'), ('Low', 'Low'), ('Lowest', 'Lowest')], max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='hozadmin.client')),
            ],
        ),
    ]
