# Generated by Django 5.1.6 on 2025-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0004_alter_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('On Going', 'On Going'), ('Up Coming', 'Up Coming'), ('Completed', 'Completed')], default='On Going', max_length=255, null=True),
        ),
    ]
