# Generated by Django 5.1.6 on 2025-02-19 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0006_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='days_remaining',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Up Coming', 'Up Coming'), ('On Going UI', 'On Going UI'), ('On Going Dev', 'On Going Dev'), ('Completed', 'Completed')], default='Up Coming', max_length=255, null=True),
        ),
    ]
