# Generated by Django 5.1.6 on 2025-02-20 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0009_alter_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
