# Generated by Django 5.1.6 on 2025-02-20 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0011_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Designation',
            new_name='designation',
        ),
        migrations.AlterField(
            model_name='employee',
            name='acc_no',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Account Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='ifsc',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='IFSC Code'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateField(blank=True, null=True, verbose_name='Joining Date'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Full Name'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pan',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='PAN Number'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='upi_id',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='UPI ID'),
        ),
    ]
