# Generated by Django 5.1.6 on 2025-02-20 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0012_rename_designation_employee_designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_logos/'),
        ),
    ]
