# Generated by Django 5.1.6 on 2025-02-21 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0013_employee_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
    ]
