# Generated by Django 5.1.6 on 2025-02-21 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hozadmin', '0016_employee_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(blank=True, choices=[('UI/UX Design', 'UI/UX Design'), ('Website Development', 'Website Development'), ('SEO', 'SEO'), ('Social Media', 'Social Media')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('UI/UX Design', 'UI/UX Design'), ('Website Development', 'Website Development'), ('SEO', 'SEO'), ('Social Media', 'Social Media')], max_length=255, null=True),
        ),
    ]
